version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./supervisord.conf:/etc/supervisor/supervisord.conf
      - ./conf.d:/etc/supervisor/conf.d
    networks:
      - laravel
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql        # correspond au nom du service MySQL
      DB_PORT: 3306
      DB_DATABASE: laravel_db
      DB_USERNAME: laravel_user
      DB_PASSWORD: secret_pass
    working_dir: /var/www/html
    command: /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
    restart: always

  mysql:
    image: mysql:5.7
    container_name: laravel-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret_pass
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: secret_pass
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel-phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: secret_pass
    networks:
      - laravel
    depends_on:
      - mysql

networks:
  laravel: {}

volumes:
  mysql_data: {}
